<a href="https://colab.research.google.com/github/PARTHIBAN-007/Transformers/blob/main/Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

In [3]:
from transformers import pipeline
classifier = pipeline("sentiment-analysis")

classifier(
    [
        "Hugging Face course on Transformers is a Goldmine for developers",
        "bad feel for joining late th this course"
    ]
)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9968780279159546},
 {'label': 'NEGATIVE', 'score': 0.9996546506881714}]

In [4]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [6]:
raw_inputs = [
     "Hugging Face course on Transformers is a Goldmine for developers",
      "bad feel for joining late th this course"
]

inputs = tokenizer(raw_inputs ,padding =True , truncation =True,return_tensors= "pt" )
print(inputs)

{'input_ids': tensor([[  101, 17662,  2227,  2607,  2006, 19081,  2003,  1037,  2751, 11233,
          2005,  9797,   102],
        [  101,  2919,  2514,  2005,  5241,  2397, 16215,  2023,  2607,   102,
             0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}


In [7]:
from transformers import AutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModel.from_pretrained(checkpoint)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [9]:
outputs = model(**inputs)
print(outputs.last_hidden_state.shape)

torch.Size([2, 13, 768])


In [11]:
from transformers import AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)

In [13]:
print(outputs.logits.shape)

torch.Size([2, 2])


In [14]:
print(outputs.logits)

tensor([[-2.7955,  2.9707],
        [ 4.3721, -3.5984]], grad_fn=<AddmmBackward0>)


In [15]:
import torch

predictions = torch.nn.functional.softmax(outputs.logits,dim=-1)
print(predictions)

tensor([[3.1220e-03, 9.9688e-01],
        [9.9965e-01, 3.4537e-04]], grad_fn=<SoftmaxBackward0>)


In [17]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

### Transformer

In [18]:
from transformers import BertConfig , BertModel

config = BertConfig()
model = BertModel(config)


In [19]:
print(config)

BertConfig {
  "_attn_implementation_autoset": true,
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.48.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}



In [20]:
model = BertModel.from_pretrained("bert-base-uncased")


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [21]:
sequences = ["Hello","Cool","Nice"]


encoded_sequences = [
    [101, 7592, 999, 102],
    [101, 4658, 1012, 102],
    [101, 3835, 999, 102],
]

model_inputs = torch.tensor(encoded_sequences)

In [23]:
output = model(model_inputs)
print(output)

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-5.0937e-02,  1.0882e-01, -1.4107e-01,  ..., -1.2431e-01,
          -8.0330e-02,  2.8579e-01],
         [-6.7714e-01, -5.4644e-01,  8.7821e-02,  ..., -5.7526e-02,
           3.5945e-02, -3.0803e-01],
         [-1.0903e+00, -9.9962e-01, -5.6360e-01,  ...,  3.2317e-01,
          -2.7725e-01, -1.4627e-01],
         [ 8.3018e-01,  5.0070e-02, -2.2515e-01,  ...,  3.2161e-01,
          -6.4891e-01, -2.4565e-01]],

        [[-2.8582e-01, -1.8636e-02,  7.9946e-02,  ..., -3.2150e-01,
           3.1830e-01,  5.7760e-01],
         [ 4.5425e-01, -5.5395e-01,  3.9479e-01,  ..., -2.2183e-01,
           1.8811e-01,  1.0380e-01],
         [-2.7685e-01, -1.0924e+00,  2.2841e-01,  ...,  2.6004e-01,
           3.7289e-01,  6.6872e-02],
         [ 9.7986e-01, -2.8927e-02, -1.4129e-01,  ...,  3.6114e-01,
          -6.3582e-01, -1.5222e-01]],

        [[-7.1076e-04,  1.6308e-01, -1.2002e-01,  ..., -1.5940e-02,
          -5.3252e-02,  3

### Tokenizers

In [24]:
tokenizer_text = "hugging Face Course on Transformers".split()
print(tokenizer_text)

['hugging', 'Face', 'Course', 'on', 'Transformers']


In [26]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-cased")


vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

In [27]:
tokenizer("hugging Face Course on Transformers")

{'input_ids': [101, 19558, 10289, 10176, 1113, 25267, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

In [2]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
sequence = "hugging Face Course on Transformers"
tokens = tokenizer.tokenize(sequence)
print(tokens)

sequence = "hugging Face Course on Transformer"
tokens = tokenizer.tokenize(sequence)

print(tokens)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

['hugging', 'Face', 'Course', 'on', 'Transformers']
['hugging', 'Face', 'Course', 'on', 'Trans', '##former']


In [3]:
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

[19558, 10289, 10176, 1113, 13809, 23763]


In [5]:
decoded_tokens = tokenizer.decode([19558, 10289, 10176, 1113, 13809, 23763])
print(decoded_tokens)

hugging Face Course on Transformer


### Multiple Sequences

In [9]:
import torch
from transformers import AutoTokenizer , AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "Hugging Face Course on Transformer.Eagerly Waiting for Agentic AI Course"

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor(ids)
#model(input_ids)

the above code will through error because we are passing single sequence to the model but the model expects multiple sequence by default

In [10]:
tokenized_inputs = tokenizer(sequence,return_tensors ="pt")
print(tokenized_inputs["input_ids"])

tensor([[  101, 17662,  2227,  2607,  2006, 10938,  2121,  1012, 17858,  3403,
          2005,  4005,  2594,  9932,  2607,   102]])


In [13]:
import torch
from transformers import AutoTokenizer , AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = "Hugging Face Course on Transformer.Eagerly Waiting for Agentic AI Course"


tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = torch.tensor([ids])
print("Input ID's : ",input_ids)

output = model(input_ids)
print("Ouput : ",output.logits)

Input ID's :  tensor([[17662,  2227,  2607,  2006, 10938,  2121,  1012, 17858,  3403,  2005,
          4005,  2594,  9932,  2607]])
Ouput :  tensor([[ 3.1135, -2.6150]], grad_fn=<AddmmBackward0>)


In [14]:
batched_ids = [
    [200, 200, 200],
    [200, 200]
]



padding_id = 100

batched_ids = [
    [200, 200, 200],
    [200, 200, padding_id],
]

In [15]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence1_ids = [[200, 200, 200]]
sequence2_ids = [[200, 200]]
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

print(model(torch.tensor(sequence1_ids)).logits)
print(model(torch.tensor(sequence2_ids)).logits)
print(model(torch.tensor(batched_ids)).logits)

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


tensor([[ 1.5694, -1.3895]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)
tensor([[ 1.5694, -1.3895],
        [ 1.3374, -1.2163]], grad_fn=<AddmmBackward0>)


In [16]:
batched_ids = [
    [200, 200, 200],
    [200, 200, tokenizer.pad_token_id],
]

attention_mask = [
    [1, 1, 1],
    [1, 1, 0],
]

outputs = model(torch.tensor(batched_ids), attention_mask=torch.tensor(attention_mask))
print(outputs.logits)

tensor([[ 1.5694, -1.3895],
        [ 0.5803, -0.4125]], grad_fn=<AddmmBackward0>)


### complete Pipeline and transformers

In [20]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

sequence = "Hugging Face Course on Transformer.Eagerly Waiting for Agentic AI Course"

model_inputs = tokenizer(sequence)

In [21]:
sequence = ["Hugging Face Course on Transformer.Eagerly Waiting for Agentic AI Course",
            "Eagerly waiting for Agentic AI Course"]

model_inputs = tokenizer(sequence)

In [26]:
#Pad the sequence up to the max length of the sequence
model_inputs = tokenizer(sequence,padding="longest")

#pad the sequence up to the maximum lenth of the model (BERT-512)
model_inputs = tokenizer(sequence,padding="max_length")

#pad the sequence up to the specified maximum lenth
model_inputs = tokenizer(sequence,padding="max_length",max_length=8)

In [27]:
sequence = ["Hugging Face Course on Transformer.Eagerly Waiting for Agentic AI Course",
            "Eagerly waiting for Agentic AI Course"]

# truncate the sequence that are longer than model's max length
model_inputs = tokenizer(sequence,truncation =True)

# truncate the sequence that are longer than Specified max length
model_inputs = tokenizer(sequence,max_length =7 ,truncation =True)

In [29]:
# Returns PyTorch tensors
model_inputs = tokenizer(sequence, padding=True, return_tensors="pt")

# Returns TensorFlow tensors
model_inputs = tokenizer(sequence, padding=True, return_tensors="tf")

# Returns NumPy arrays
model_inputs = tokenizer(sequence, padding=True, return_tensors="np")

In [30]:
sequence = "Hugging Face Course on Transformer.Eagerly Waiting for Agentic AI Course"

model_inputs = tokenizer(sequence)
print(model_inputs["input_ids"])

tokens = tokenizer.tokenize(sequence)
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

[101, 17662, 2227, 2607, 2006, 10938, 2121, 1012, 17858, 3403, 2005, 4005, 2594, 9932, 2607, 102]
[17662, 2227, 2607, 2006, 10938, 2121, 1012, 17858, 3403, 2005, 4005, 2594, 9932, 2607]


In [32]:
print("Tokenizer Implementaion : " ,tokenizer.decode(model_inputs["input_ids"]))
print("Manual Implementaion : " ,tokenizer.decode(ids))

Tokenizer Implementaion :  [CLS] hugging face course on transformer. eagerly waiting for agentic ai course [SEP]
Manual Implementaion :  hugging face course on transformer. eagerly waiting for agentic ai course


In [36]:
import torch
from transformers import AutoModelForSequenceClassification , AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

sequence = ["Hugging Face Course on Transformer.Eagerly Waiting for Agentic AI Course",
            "Eagerly waiting for Agentic AI Course"]

tokens = tokenizer(sequence, padding=True,truncation = True,return_tensors="pt")
output = model(**tokens)
print(output)

SequenceClassifierOutput(loss=None, logits=tensor([[-2.3938,  2.5584],
        [ 1.6820, -1.4928]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)
